services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  proman:
    build:
      context: ..
      dockerfile: server/Dockerfile
    restart: always
    environment:
      MYSQL_DSN: ${MYSQL_DSN}
      REDIS_ADDR: redis:6379
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080

volumes:
  mysql-data:
  redis-data:
